### ISSUE TITLE
ng2-datepicker-bootstrap lists no main file and has no index.js, so it can't be directly required.

### ISSUE THREAD

**Issue by quackerjeff** [rodolfocop/ng2-datepicker-bootstrap#3]
Can you address this?  I end up getting errors that DatePickerModule cannot be found.

**Comment by rodolfocop** [comment]
Hi, could you be more specific in the problem? 
This component does not have a js file, install and add it to your Module. 

You are using a final version of the angular(4.0.0)?

**Comment by Tahirkhan56** [comment]
Hi, I just installed it and use it into my module but I have following error.
 Error: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:49863/app/app.module.js:14:36)
	    at eval (http://localhost:49863/app/app.module.js:41:4)
	    at eval (http://localhost:49863/app/app.module.js:42:3)
	Evaluating http://localhost:49863/ng2-datepicker-bootstrap
	Evaluating http://localhost:49863/app/app.module.js
	Evaluating http://localhost:49863/app/main.js
	Error loading http://localhost:49863/app/main.js
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:49863/app/app.module.js:14:36)
	    at eval (http://localhost:49863/app/app.module.js:41:4)
	    at eval (http://localhost:49863/app/app.module.js:42:3)
	Evaluating http://localhost:49863/ng2-datepicker-bootstrap
	Evaluating http://localhost:49863/app/app.module.js
	Evaluating http://localhost:49863/app/main.js
	Error loading http://localhost:49863/app/main.js

Could you tell me the Systemjs configuration please? because I did not found any index.js or main.js file to specify in systemjs packages section.

**Comment by yongbin999** [comment]
you need something like this for angular4 that need to reference the system.config.js

https://github.com/kekeh/mydatepicker

**Comment by Tahirkhan56** [comment]
Thanks you Yong Liang. I will try it today
